config/routes.rb
Rails.application.routes.draw do
  resources :steps
  devise_for :users
  root 'page#index'
  resources :collaborators
  resources :projects
  resources :tasks 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
    has_many :tasks
    accepts_nested_attributes_for :tasks
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Un nouveau projet a été créé.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Projet mis à jour.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Le projet a été détruit.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:project_name)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<div class="container">
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Nom_du_projet, :class => "col-sm-2 col-form-label" %>
  <div class="col-sm-10">
    <%= form.text_field :project_name, :class => "form-control" %>
  </div>
  </div>

  <div class="actions" style="margin-top: 30px; margin-left: 15px">
    <%= form.submit :Validation, class: 'btn btn-primary' %>
  </div>
<% end %>
</div>

app/views/projects/edit.html.erb
<div class="container">
<h1>Modifier le projet</h1>

<%= render 'form', project: @project %>


</div>

app/views/projects/index.html.erb
<div class="container">
<div class="animated fadeIn delay-1s">
<p id="notice"><%= notice %></p>

<h1>Projets</h1>

<table class="table">
  <thead>
    <tr>
      <th>Nom du projet</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.project_name, project %></td>
      
        <td><td>
          
        <div class="luka" style="text-align: right;">  
        <%= link_to edit_project_path(project) do %>
        <%= fa_icon 'edit', :style => "font-size: 25px; color: #444444;" %>
        <% end %>
        
        <%= link_to project, method: :delete, data: { confirm: 'Are you sure?' } do %>
        <%= fa_icon 'trash', :style => "font-size: 25px; color: #444444" %>
        <% end %>
        </div>
        
        </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '+ Ajouter un nouveau projet', new_project_path, :class => "btn btn-primary btn-sm", :style => "color: white" %>
</div>
</div>

app/views/projects/new.html.erb
<div class="container">
<h1>Nouveau projet</h1>

<%= render 'form', project: @project %>

</div>

app/views/projects/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <strong>Project name:</strong>
  <%= @project.project_name %>
</p>

</div>