config/routes.rb
Rails.application.routes.draw do
  resources :steps
  devise_for :users
  root 'page#index'
  resources :collaborators
  resources :projects
  resources :tasks 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/step.rb
class Step < ApplicationRecord
    has_many :tasks
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  before_action :set_step, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /steps
  # GET /steps.json
  def index
    if current_user.admin == true
    @steps = Step.all
    else
      redirect_to root_path
    end
  end

  # GET /steps/1
  # GET /steps/1.json
  def show
    if current_user.admin == false
      redirect_to root_path
    end
  end

  # GET /steps/new
  def new
    if current_user.admin == true
      @step = Step.new
    else
      redirect_to root_path
    end
  end

  # GET /steps/1/edit
  def edit
    if current_user.admin == false
      redirect_to root_path
    end
  end

  # POST /steps
  # POST /steps.json
  def create
    @step = Step.new(step_params)

    respond_to do |format|
      if @step.save
        format.html { redirect_to @step, notice: 'Step was successfully created.' }
        format.json { render :show, status: :created, location: @step }
      else
        format.html { render :new }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /steps/1
  # PATCH/PUT /steps/1.json
  def update
    if current_user.admin == true
    respond_to do |format|
      if @step.update(step_params)
        format.html { redirect_to @step, notice: 'Step was successfully updated.' }
        format.json { render :show, status: :ok, location: @step }
      else
        format.html { render :edit }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
      end
    else
      redirect_to root_path
    end
  end

  # DELETE /steps/1
  # DELETE /steps/1.json
  def destroy
    if current_user.admin == true
    @step.destroy
    respond_to do |format|
      format.html { redirect_to steps_url, notice: 'Step was successfully destroyed.' }
      format.json { head :no_content }
    end
    else
      redirect_to root_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_step
      @step = Step.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def step_params
      params.require(:step).permit(:step_name)
    end
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/steps/_form.html.erb
<%= form_with(model: step, local: true) do |form| %>
  <% if step.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(step.errors.count, "error") %> prohibited this step from being saved:</h2>

      <ul>
      <% step.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nouvelle_etape %>
    <%= form.text_field :step_name %>
  </div>

  <div class="actions">
    <%= form.submit :Validation, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/steps/edit.html.erb
<h1>Modifier la table Steps</h1>

<%= render 'form', step: @step %>

app/views/steps/index.html.erb
<div class="container" style="padding-bottom: 100px">
<p id="notice"><%= notice %></p>

<h1>Etape</h1>

<table class="table">
  <thead>
    <tr>
      <th>Step name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @steps.each do |step| %>
      <tr>
        <td><%= step.step_name %></td>
        <td><%= link_to 'voir', step %></td>
        <td><%= link_to 'modifier', edit_step_path(step) %></td>
        <td><%= link_to 'supprimer', step, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'nouvelle étape', new_step_path, class: 'btn btn-primary'%>
</div>

app/views/steps/new.html.erb
<h1>Nouvelle étape</h1>

app/views/steps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom de l'étape:</strong>
  <%= @step.step_name %>
</p>