config/routes.rb
Rails.application.routes.draw do
  resources :steps
  devise_for :users
  root 'page#index'
  resources :collaborators
  resources :projects
  resources :tasks 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto" style="height: 60px; padding-top: 8px">
          <%= link_to image_tag("logo-2.png", :alt => "Image Description", :class => "width: 200px"), root_path %>
        </ul>
        
        <ul class="navbar-nav ml-auto">
              
              
        <% if user_signed_in? && current_user.admin? %>
              <li class="nav-item">
                <div class="nav-link"><%= link_to 'collaborateurs', collaborators_path %></div>
              </li>
              <li class="nav-item">
                <div class="nav-link" style="display: none"><%= link_to 's\'inscrire', new_user_registration_path %></div>
              </li>
        <% end %>      
              
        <% if user_signed_in? %>
              <li class="nav-item">
                <div class="nav-link"><%= link_to 'projets', projects_path %></div>
              </li>
              <li class="nav-item">
                <div class="nav-link"><%= link_to 'tâches', tasks_path %></div>
              </li>
              <li class="nav-item">
                <div class="nav-link"><%= link_to 'se deconnecter', destroy_user_session_path, method: :delete %></div>
              </li>
        <% end %>
        </ul>
      </div>
    </div>
</nav>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto" style="height: 60px; padding-top: 8px">
          <%= link_to image_tag("logo-2.png", :alt => "Image Description", :class => "width: 200px"), root_path %>
        </ul>
        
        <ul class="navbar-nav ml-auto">
              
              
        <% if user_signed_in? && current_user.admin? %>
              <li class="nav-item">
                <div class="nav-link"><%= link_to 'collaborateurs', collaborators_path %></div>
              </li>
              <li class="nav-item">
                <div class="nav-link" style="display: none"><%= link_to 's\'inscrire', new_user_registration_path %></div>
              </li>
        <% end %>      
              
        <% if user_signed_in? %>
              <li class="nav-item">
                <div class="nav-link"><%= link_to 'projets', projects_path %></div>
              </li>
              <li class="nav-item">
                <div class="nav-link"><%= link_to 'tâches', tasks_path %></div>
              </li>
              <li class="nav-item">
                <div class="nav-link"><%= link_to 'se deconnecter', destroy_user_session_path, method: :delete %></div>
              </li>
        <% end %>
        </ul>
      </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lundi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= yield %>
  </body>
</html>